title: "Huihui Li's Homepage"
page-top-title: Huihui Li
top-section-bg-text: School of Automation, Northwestern Polytechnical University.
home-subtitle: Huihui Li(李晖晖)&ensp;|&ensp;Associate Professor
copyright-text: '&copy; Yourname 2023-2025. All Rights Reserved.'
